#!/usr/bin/lua

local function read_file(path)
    local file = io.open(path, "r")
    if file then
        local text = file:read("*all")
        file:close()
        return text
    else
        return nil
    end
end

local function get_blocks(text)
    local blocks = {}
    local regex = "```%s*([^%s]+)%s*([^%s]*)%s*\n(.-)```"

    for lang, tag, body in text:gmatch(regex) do
        local block = {
            lang = lang,
            tag = tag,
            body = body
        }
        table.insert(blocks, block)
    end

    return blocks
end

local function find_snippet(blocks, tag)
    for _, block in ipairs(blocks) do
        if block.tag == "#" .. tag then
            return block
        end
    end

    return nil
end

local function run_snippet(path, tag)
    require("urynus_config")
    local blocks = get_blocks(read_file(path))
    local block = find_snippet(blocks, tag)

    if block then
        local file_name = SNIPPETS[block.lang].name
        local file = io.open(file_name, "w")
        if file then
            file:write(block.body)
            file:close()
        end

        os.execute(SNIPPETS[block.lang].script)
        os.remove(file_name)
    end
end

local function tangle_files(path)
    local blocks = get_blocks(read_file(path))
    local files = {}
    for _, block in ipairs(blocks) do
        local file
        if block.tag:sub(1,1) ~= "#" then
            if files[block.tag] then
                file = io.open(block.tag, "a")
            else
                file = io.open(block.tag, "w")
                files[block.tag] = true
            end
        end

        if file then
            file:write(block.body .. "\n")
            file:close()
        end
    end
end

local function init_project()
    local file = io.open("urynus_config.lua", "w")
    if file then
        file:write(
[[SNIPPETS = {
    ["python"] = {
        name   = "snippet.py",
        script = "python3 snippet.py",
    }
}]])
        file:close()
    end
end

local function main()
    local mode = arg[1]

    if mode == "snip" then
        run_snippet(arg[2], arg[3])
    elseif mode == "tangle" then
        tangle_files(arg[2])
    elseif mode == "init" then
        init_project()
    else
        print("Not an accepted command. Try init, snip, or tangle")
    end
end

main()
