#!/usr/bin/perl

open FH, '<', $ARGV[1] or die $!;
    my @matches = do { local $/; <FH> } =~ /```(.*?)```/gs;
close FH;

my @blocks;
foreach $match (@matches) {
    push @blocks, split(' ', $match, 3);
}

if ($ARGV[0] eq 'tangle') {
    my @opened;
    for (my $i = 0; $i < @blocks; $i += 3) {
        my ($dest, $code) = @blocks[$i+1..$i+2];
    
        if (substr($dest, 0, 1) ne '#') {
            if (grep {$_ == $dest} @opened) {
                open FH, '>>', $dest or die $!;
            } else {
                push @opened, $dest;
                open FH, '>', $dest or die $!;
            }
            print FH "$code\n";
            close FH;
        } 
    }

} elsif ($ARGV[0] eq 'snip') {
    my $i = grep { $blocks[$_] eq "$ARGV[2]" } 0..$#blocks;
    open FH, '>', 'snippet' or die $!;
        print FH "$blocks[$i+1]\n";
    close FH;
    system "bash urynus_config $blocks[$i-1]";
    unlink 'snippet'

} elsif ($ARGV[0] eq 'init') {
    open FH, '>', 'urynus_config' or die $!;
    print FH '
#!/bin/bash 
case $1 in
    python) python3 snippet ;;
esac';
    close FH;
}
